# Generated by Django 3.1.3 on 2020-11-16 23:49

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('thumbsUp', models.IntegerField(default=0)),
                ('thumbsDown', models.IntegerField(default=0)),
            ],
            managers=[
                ('Movies', django.db.models.manager.Manager()),
            ],
        ),
    ]
